// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Miniflow.Migrations;

[DbContext(typeof(AppDbContext))]
  partial class AppDbContextModelSnapshot : ModelSnapshot
  {
      protected override void BuildModel(ModelBuilder modelBuilder)
      {
#pragma warning disable 612, 618
          modelBuilder
              .HasAnnotation("ProductVersion", "8.0.11")
              .HasAnnotation("Relational:MaxIdentifierLength", 63);

          NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

          modelBuilder.Entity("Miniflow_Backend.User", b =>
              {
                  b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("integer");

                  NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                  b.Property<string>("Name")
                      .IsRequired()
                      .HasColumnType("text");

                  b.HasKey("Id");

                  b.ToTable("Users");
              });
#pragma warning restore 612, 618
      }
  }
